# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_images', upload_to=''),
        ),
    ]
