# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160916_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_images/', upload_to=''),
        ),
    ]
