# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160916_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/media/post_images/', upload_to=''),
        ),
    ]
