# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160916_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='/Users/Jarvis/Desktop/Ingegnemagia/media'),
        ),
    ]
