# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20160916_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../../../media/placehold_900x300.png', upload_to=''),
        ),
    ]
